# Generated by Django 4.0.4 on 2022-05-03 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stephunter', '0003_alter_company_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('NIS', 'Не ищу работу'), ('OTO', 'Открыт к предложениям'), ('RD', 'Ищу работу')], max_length=3)),
                ('salary', models.IntegerField()),
                ('qualification', models.CharField(choices=[('JUN', 'Junior'), ('MID', 'Middle'), ('SNR', 'Senior')], max_length=3)),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('portfolio', models.CharField(max_length=200)),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_owner', to=settings.AUTH_USER_MODEL)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_spec', to='stephunter.specialty')),
            ],
        ),
    ]
